"""add reg_date

Revision ID: 8e2a501691ac
Revises: 8f89efa85aa3
Create Date: 2024-08-08 16:03:33.253272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e2a501691ac"
down_revision: Union[str, None] = "8f89efa85aa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "photos",
         sa.Column(
            "pub_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "reg_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reg_date")
    op.alter_column(
        "photos",
        "pub_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
